version: '3.4'

networks:
  happy_software:
    name: happy_network

x-main: &main
  tty: true
  stdin_open: true
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
  volumes:
    - '.:/app'
  environment:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    ONBOARDING_TOKEN: fake123
    HAPPY_HOUSE_API_TOKEN: fake123
  networks:
    - default
    - happy_software
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: 'postgres:11.1-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    volumes:
      - 'redis:/data'

  app:
    <<: *main
    ports:
      - "3001:3001"

volumes:
  postgres:
  redis:
