name: Ruby

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
